Repository Lets-code-with-us/scamwebsiteV1, pull requests merged in 2024-10, with the labels that each got.

#22 Update README.md
  .github/ISSUE_TEMPLATE/issue_form.yml
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, under-review

#20 Add github action #17
  .github/workflows/deploy.yml
Labels: hacktoberfest, hacktoberfest-accepted, under-review

#10 Added zod validation
  package-lock.json
  package.json
  src/app/api/user/contact/route.ts
  src/app/api/user/email/route.ts
  src/app/api/user/login/route.ts
  src/app/api/user/signin/route.ts
Labels: hacktoberfest, hacktoberfest-accepted

#27 added contribution.md file
  contribution.md
Labels: hacktoberfest, hacktoberfest-accepted, under-review

#32 resolve error of sign in
  src/app/api/user/login/route.ts
  src/app/api/user/signin/route.ts
Labels: bug, hacktoberfest, hacktoberfest-accepted

#34 resolve function issue in profile function
  src/app/api/user/profile/route.ts
Labels: bug, hacktoberfest, hacktoberfest-accepted

#36 added turbo repos
  .gitignore
  .husky/pre-commit
  package-lock.json
  package.json
  src/app/api/user/profile/route.ts
  turbo.json
Labels: good first issue, help wanted, hacktoberfest, hacktoberfest-accepted

#31 fix: like display and apis and render models only once
  src/components/component/BlogLayout.tsx
  src/models/blogModel.js
  src/models/commentModel.js
  src/models/contactModel.js
  src/models/likeModel.js
  src/models/newLetterModel.js
  src/models/oAuthModel.js
  src/models/profileModel.js
  src/models/reportModel.js
  src/models/userBio.js
  src/models/userModel.js
Labels: hacktoberfest, hacktoberfest-accepted, under-review

#39 resolve the bcrypt and signup issue
  contribution.md
  package-lock.json
  package.json
  src/app/api/user/login/route.ts
  src/app/api/user/profile/route.ts
  src/app/api/user/signin/route.ts
  src/app/profile/page.tsx
Labels: bug, hacktoberfest, hacktoberfest-accepted

#38 Fix Newsletter Email Submission: Add Feedback for Success and Error States
  package-lock.json
  package.json
  src/components/component/Cta.tsx
  src/db/dbConnect.ts
  tsconfig.json
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#40 resolve the database connection
  src/db/dbConnect.ts
Labels: hacktoberfest, hacktoberfest-accepted

#33 Added initial JEST config with test cases
  .gitignore
  jest.config.ts
  jest.setup.ts
  package-lock.json
  package.json
  src/app/page.test.tsx
  src/app/page.tsx
  src/components/component/Hero.test.tsx
  tsconfig.json
Labels: hacktoberfest, hacktoberfest-accepted

#56 updated the package.json file
  .husky/pre-commit
  package.json
  src/components/component/Feature.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#58 resolve the login error
  src/app/login/page.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#60 Resolved the login issue and add zustand
  package-lock.json
  package.json
  src/app/login/page.tsx
  src/components/component/NavBar.tsx
  src/context/useAuthStore.ts
Labels: bug, hacktoberfest, hacktoberfest-accepted

#66 Update README.md with available scripts
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#44 fixed #29 : Improve the UI/layout of login page
  src/app/login/page.tsx
  src/components/component/Footer.tsx
Labels: hacktoberfest, hacktoberfest-accepted, under-review

#78 Docs : Added contributor section to README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#90 Enhance icons for feature section in components/component/Feature.tsx
  src/components/component/Feature.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#92 Feature : Implemented an interactive FAQ section on the homepage for …
  src/components/component/Cta.tsx
  src/components/component/Faq.tsx
  src/data/faqData.json
Labels: hacktoberfest, hacktoberfest-accepted

#91 ADDED CODE_OF_CONDUCT file to the repository
  CODE_OF_CONDUCT.md
Labels: hacktoberfest, hacktoberfest-accepted

#94 update the github hook
  .husky/pre-commit
  CODE_OF_CONDUCT.md
  README.md
  src/components/component/BlogLayout.tsx
  src/components/component/Cta.tsx
  src/components/component/Faq.tsx
  src/components/component/Feature.tsx
  src/data/faqData.json
Labels: hacktoberfest, hacktoberfest-accepted

#47 Fix: Password Hashing and JWT Validation in forgetPassword Route
  src/app/api/user/forgetpassword/route.ts
Labels: hacktoberfest, hacktoberfest-accepted

#88 added cron job api to send email to registered user about new blogs published
  src/api/sendEmail.ts
Labels: hacktoberfest, hacktoberfest-accepted

#102 loginLoader added
  src/app/login/page.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#100 improve readme + Fix Leerob pfp
  README.md
  next.config.mjs
  src/app/api/user/report/route.ts
  src/components/component/Cta.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#105 Fixed about page
  next.config.mjs
Labels: hacktoberfest, hacktoberfest-accepted

#110 Add FAQ section to enhance user understanding
  Add FAQ Section to Documentation.
Labels: hacktoberfest, hacktoberfest-accepted

#103 fixed contact's form input visiblilty
  src/app/contact/page.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#97 email verification
  src/app/api/user/verifyEmail/[email]/route.ts
  src/app/api/user/verifyEmail/route.ts
  src/models/userModel.js
Labels: hacktoberfest, hacktoberfest-accepted
